### ISSUE TITLE
Unhandled exception: BakedFileSystem empty: no files in src/core/node/virtual_file_system/api/v1

### ISSUE THREAD

**Issue by q9f** [Axentro/Axentro#384] opened 2021-02-15 13:57 UTC
## Checklist
- [x] You've tried with the latest version of Axentro `v2.0.2`
- [x] You've confirmed this issue is not a duplicate

## Description
The binaries would refuse to execute any command with a `BakedFileSystem` empty exception.

## Environment
- Using docker: no
- Crystal version: `0.36.1`
- Shards: `0.13.0`
- LLVM: `10.0.1`
- Default target: `x86_64-pc-linux-gnu`
- Arch Linux, GNU/Linux kernel `5.10.13-arch1-2`

## Command Lines and results
```
~/.opt/Axentro/Axentro/bin tags/v2.0.2
❯ ./axe
Unhandled exception: BakedFileSystem empty: no files in /home/user/.opt/Axentro/Axentro/src/core/node/virtual_file_system/api/v1 (Exception)
  from ???
  from ???
  from __crystal_main
  from main
  from __libc_start_main
  from _start
  from ???
```

```
~/.opt/Axentro/Axentro/bin tags/v2.0.2
❯ ll /home/user/.opt/Axentro/Axentro/src/core/node/virtual_file_system/api/v1
total 780K
4.0K drwxr-xr-x 2 user users 4.0K Feb 15 14:46 ./
4.0K drwxr-xr-x 3 user users 4.0K Feb 15 14:46 ../
772K -rw-r--r-- 1 user users 770K Feb 15 14:46 index.html
```

**Comment by q9f** [comment] 2021-02-15 14:04
```
~/.opt/Axentro/Axentro/bin tags/v2.0.2
❯ gdb ./axe
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./axe...
(gdb) r
Starting program: /home/user/.opt/Axentro/Axentro/bin/axe 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff767c640 (LWP 653113)]
[New Thread 0x7ffff6e7b640 (LWP 653114)]
[New Thread 0x7ffff667a640 (LWP 653115)]
[New Thread 0x7ffff5e79640 (LWP 653116)]
[New Thread 0x7ffff5678640 (LWP 653117)]
[New Thread 0x7ffff4e77640 (LWP 653118)]
[New Thread 0x7ffff4676640 (LWP 653119)]
[New Thread 0x7ffff3e75640 (LWP 653120)]
[New Thread 0x7ffff3674640 (LWP 653121)]
[New Thread 0x7ffff2e73640 (LWP 653122)]
[New Thread 0x7ffff2672640 (LWP 653123)]
[New Thread 0x7ffff1e71640 (LWP 653124)]
[New Thread 0x7ffff1670640 (LWP 653125)]
[New Thread 0x7ffff0e6f640 (LWP 653126)]
[New Thread 0x7ffff066e640 (LWP 653127)]
Unhandled exception: BakedFileSystem empty: no files in /home/user/.opt/Axentro/Axentro/src/core/node/virtual_file_system/api/v1 (Exception)
  from /home/user/.opt/Axentro/Axentro/src/core/dapps/build_in/hra.cr:18:3 in '__crystal_main'
  from /usr/lib/crystal/crystal/main.cr:110:5 in 'main_user_code'
  from /usr/lib/crystal/crystal/main.cr:96:7 in 'main'
  from /usr/lib/crystal/crystal/main.cr:119:3 in 'main'
  from __libc_start_main
  from _start
  from ???
[Thread 0x7ffff066e640 (LWP 653127) exited]
[Thread 0x7ffff0e6f640 (LWP 653126) exited]
[Thread 0x7ffff1670640 (LWP 653125) exited]
[Thread 0x7ffff1e71640 (LWP 653124) exited]
[Thread 0x7ffff2e73640 (LWP 653122) exited]
[Thread 0x7ffff3674640 (LWP 653121) exited]
[Thread 0x7ffff3e75640 (LWP 653120) exited]
[Thread 0x7ffff4676640 (LWP 653119) exited]
[Thread 0x7ffff4e77640 (LWP 653118) exited]
[Thread 0x7ffff5678640 (LWP 653117) exited]
[Thread 0x7ffff5e79640 (LWP 653116) exited]
[Thread 0x7ffff667a640 (LWP 653115) exited]
[Thread 0x7ffff6e7b640 (LWP 653114) exited]
[Thread 0x7ffff767c640 (LWP 653113) exited]
[Thread 0x7ffff769e380 (LWP 653109) exited]
[Inferior 1 (process 653109) exited with code 01]
```

**Comment by q9f** [comment] 2021-02-15 14:11
```
~/.opt/Axentro/Axentro/bin tags/v2.0.2
❯ ./axen                                                              
Unhandled exception: BakedFileSystem empty: no files in /home/user/.opt/Axentro/Axentro/src/core/node/virtual_file_system/api/v1 (Exception)
  from /home/user/.opt/Axentro/Axentro/src/core/dapps/build_in/hra.cr:18:3 in '__crystal_main'
  from /usr/lib/crystal/crystal/main.cr:110:5 in 'main_user_code'
  from /usr/lib/crystal/crystal/main.cr:96:7 in 'main'
  from /usr/lib/crystal/crystal/main.cr:119:3 in 'main'
  from __libc_start_main
  from _start
  from ???

~/.opt/Axentro/Axentro/bin tags/v2.0.2
❯ ./axem
Unhandled exception: BakedFileSystem empty: no files in /home/user/.opt/Axentro/Axentro/src/core/node/virtual_file_system/api/v1 (Exception)
  from /home/user/.opt/Axentro/Axentro/lib/sqlite3/src/sqlite3/driver.cr:7:1 in '__crystal_main'
  from /usr/lib/crystal/crystal/main.cr:110:5 in 'main_user_code'
  from /usr/lib/crystal/crystal/main.cr:96:7 in 'main'
  from /usr/lib/crystal/crystal/main.cr:119:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

**Comment by kingsleyh** [comment] 2021-02-15 19:15
hmm thanks - first time I've seen this issue

**Comment by kingsleyh** [comment] 2021-02-16 10:42
I tried to put a fix for this - but not really sure how it occurs - I think it might be an issue with the baked file system shard or some kind of timing issue during building. I thought the fix had worked but we still get this happening intermittently on the gihub build actions CI - although we don't see it on the circleci build. So still unsure what the problem is - it's intermittent tho

**Comment by q9f** [comment] 2021-02-16 10:50
#386 fixed it for me though

**Closed** 2021-02-16 12:53 UTC
